### ISSUE TITLE
wrong average quality?

### ISSUE THREAD

**Issue by lcmmichielsen** [wdecoster/nanomath#11]
I was trying to rewrite your python function to a julia function. Having exactly the same code, I found out that the outputs were different. After calculating some scores by hand, I came to the conclusion that the python script does some rounding in between because the input quality scores are integers. This can be overcome by replacing: 

        return -10 * log(sum([10**(q / -10) for q in quals]) / len(quals), 10)

by: 

        return -10 * log(sum([10**(float(q) / -10) for q in quals]) / len(quals), 10)

**Comment by wdecoster** [comment]
I assume you tested this with a Python2, which indeed has that behavior. My code is written for Python3. 

Minimalistic demonstration:
```bash
$python2.7 -c "print(9/2)"
4
$python3 -c "print(9/2)"
4.5
```

**Comment by lcmmichielsen** [comment]
Ah indeed, you're right! 
Maybe good to mention somewhere in the README that it is written for Python3?

**Comment by wdecoster** [comment]
Hmm yes I could do that. Then again, it's specified in my READMEs of scripts which use nanomath as a dependency (NanoPlot, NanoComp, NanoFilt) - I am not aware of nanomath being used 'standalone' or by others. If your python system is reasonably up to date it would also not allow installation on a python < v3 since the setup.py contains `python_requires='>=3'`.
