### ISSUE TITLE
Formatting of output could be nicer

### ISSUE THREAD

**Issue by jvhaarst** [wdecoster/nanomath#8]
The alignment of the general summary isn't very nice.
Instead of 

```
General summary:	 
Number of reads:	3995
Total bases:	11418359
Median read length:	1221.0
Mean read length:	2858.2
Read length N50:	8676
Active channels:	933
Mean read quality:	10.2
Median read quality:	10.6
```
I would prefer
```
General summary:
Number of reads:        3,995
Total bases:            11,418,359
Median read length:     1,221.0
Mean read length:       2,858.2
Read length N50:        8,676
Active channels:        933
Mean read quality:      10.2
Median read quality:    10.6
```

Or even 
```
General summary:
Number of reads:          3,995
Total bases:         11,418,359
Median read length:       1,221.0
Mean read length:         2,858.2
Read length N50:          8,676
Active channels:            933
Mean read quality:           10.2
Median read quality:         10.6
```

**Comment by wdecoster** [comment]
Yes I agree, it's not perfect.
Note that you can render this better (on the unix command line) using 

    column -ts $'\t' NanoStats.txt

but that's just a band-aid and not a real solution.

This is however not trivial to solve because the same code is used to generate a table of stats in the case of a barcoded (`--barcoded`) summary file or for [NanoComp](https://github.com/wdecoster/nanocomp). I'll leave this issue open for a while and will look for a solution.
